name: repositories
description: Package that contains the repositories of the Portuguese Brand app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  retrofit: ^3.0.1+1
  

dev_dependencies:
  build_runner: ^2.1.5  
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.0.1
  very_good_analysis: ^3.0.0
  
